# Site settings
title: Imran's Profile
email: hi@wheelhouse.io
description: > # this means to ignore newlines until "baseurl:"
  Learning to use GitHub pages with Wheelhouse.io and Patchwork!
baseurl:"patchwork-gh-pages-24"
url: "http://ihanafi.github.io"
twitter_username: ihanafiIO
github_username:  ihanafiio
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
